Fix --list --ignored behavior
LukasKalbertodt/libtest-mimic pull request #11
Opened 2022-04-07 23:32 UTC by sunshowers

I'm trying to get libtest-mimic to work well with
[cargo-nextest](https://nexte.st/) -- see the documentation on [custom
test harnesses](https://nexte.st/book/custom-test-harnesses.html) and
nextest-rs/nextest#38. I'd love to recommend
libtest-mimic as a way to write custom test harnesses.

One of the requirements for nextest is the ability to detect ignored and
non-ignored tests during the list phase. libtest prints out just the
ignored tests if you run `--list --ignored`: make libtest-mimic do the
same.

In my testing, this appears to be the only issue blocking libtest-mimic
from working with nextest.

2022-04-07 23:32 UTC, sunshowers commented
BTW I'm also happy to port over CI to GHA if you'd like that.

2022-04-13 14:37 UTC, LukasKalbertodt requested changes
Sweet! Thanks for the PR. Looks mostly good to me, just one minor comment. 

And I did change CI to GHA and mostly merged your other PR. So please rebased and omit the "rustfmt" commit. Then this should be ready to get merged!

2022-04-13 14:37 UTC, LukasKalbertodt commented on src/printer.rs
> +            let mut cursor = Cursor::new(output);
`Vec<u8>` already implements `Write`, even without `Cursor`. So the cursor should not be necessary here, correct?

2022-04-13 18:09 UTC, sunshowers commented
Done, thanks!

2022-04-16 08:20 UTC, LukasKalbertodt approved these changes

2022-04-16 08:20 UTC, merged

2022-04-16 08:22 UTC, LukasKalbertodt commented
Thanks!

I will wait with releasing this a bit as I plan on improving the library in some other aspects before doing a new (major) release. If I don't find any time for that and forget about this, feel free to ping me again in, say, 2 weeks.

2022-05-13 13:59 UTC, LukasKalbertodt commented
Released as 0.4.0