args: Add Arguments::from_iter
LukasKalbertodt/libtest-mimic pull request #5
Opened 2020-06-06 17:40 UTC by cgwalters

I'm working on a test suite for https://github.com/ostreedev/ostree/
and I want to have both destructive tests and non-destructive
tests in the same binary.  I'm doing my own argument parsing for
the destructive tests and then want to use this crate for the non-destructive
ones.

2020-06-24 20:42 UTC, LukasKalbertodt requested changes
Seems like a useful addition. Thanks for the PR. Only one tiny nit.

2020-06-24 20:42 UTC, LukasKalbertodt commented on src/args.rs
> +    /// Like from_args(), but operates on an explicit iterator and not the global arguments.
Please use monospace here:

```suggestion
    /// Like `from_args()`, but operates on an explicit iterator and not the global arguments.
```

2020-06-24 21:59 UTC, cgwalters commented on src/args.rs
> +    /// Like from_args(), but operates on an explicit iterator and not the global arguments.
Thanks, updated!

2020-06-24 22:11 UTC, LukasKalbertodt commented
The CI failure is not due to your PR (and it's just a style thing). I will merge yours and fix that stuff on `master` later.

Also, "funny" thing I just noticed: the Travis cache was over 8GB which explains why the "downloading cache" step too forever. Ouch. Will move to GitHub actions soon anyway.

Thanks for the PR again!

2020-06-24 22:11 UTC, merged

2020-06-28 19:07 UTC, LukasKalbertodt commented
Released as 0.3.0!